# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/Vivado_PE1/MercuryZX1_PE1.srcs/sources_1/bd/MercuryZX1/ip/MercuryZX1_axi_gpio_0_0/MercuryZX1_axi_gpio_0_0.xci
# IP: The module: 'MercuryZX1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/Vivado_PE1/MercuryZX1_PE1.srcs/sources_1/bd/MercuryZX1/ip/MercuryZX1_axi_gpio_0_0/MercuryZX1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MercuryZX1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/Vivado_PE1/MercuryZX1_PE1.srcs/sources_1/bd/MercuryZX1/ip/MercuryZX1_axi_gpio_0_0/MercuryZX1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MercuryZX1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/Vivado_PE1/MercuryZX1_PE1.srcs/sources_1/bd/MercuryZX1/ip/MercuryZX1_axi_gpio_0_0/MercuryZX1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MercuryZX1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/Vivado_PE1/MercuryZX1_PE1.srcs/sources_1/bd/MercuryZX1/ip/MercuryZX1_axi_gpio_0_0/MercuryZX1_axi_gpio_0_0.xci
# IP: The module: 'MercuryZX1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/Vivado_PE1/MercuryZX1_PE1.srcs/sources_1/bd/MercuryZX1/ip/MercuryZX1_axi_gpio_0_0/MercuryZX1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MercuryZX1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/Vivado_PE1/MercuryZX1_PE1.srcs/sources_1/bd/MercuryZX1/ip/MercuryZX1_axi_gpio_0_0/MercuryZX1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MercuryZX1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/Vivado_PE1/MercuryZX1_PE1.srcs/sources_1/bd/MercuryZX1/ip/MercuryZX1_axi_gpio_0_0/MercuryZX1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MercuryZX1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
