/// Autogenerated DO NOT EDIT
///
/// (c) Koheron

#include <context_base.hpp>
#include <drivers_manager.hpp>
#include <drivers_table.hpp>

template<class Driver>
Driver& ContextBase::get() const {
    return driver_manager->get<driver_id_of<Driver>>();
}
template Common& ContextBase::get<Common>() const;

template SSFifoController& ContextBase::get<SSFifoController>() const;

template DmaSG& ContextBase::get<DmaSG>() const;

template xQSPI& ContextBase::get<xQSPI>() const;

template TopLevelDriver& ContextBase::get<TopLevelDriver>() const;
