# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/src/MercuryZX1_PE1.xdc

# Block Designs: bd/MercuryZX1/MercuryZX1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1 || ORIG_REF_NAME==MercuryZX1} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_SDRAM_0/MercuryZX1_SDRAM_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_SDRAM_0 || ORIG_REF_NAME==MercuryZX1_SDRAM_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_axi_quad_spi_1_0/MercuryZX1_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_axi_quad_spi_1_0 || ORIG_REF_NAME==MercuryZX1_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_clk_wiz_0/MercuryZX1_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_clk_wiz_0 || ORIG_REF_NAME==MercuryZX1_clk_wiz_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_system_ila_1_0/MercuryZX1_system_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_system_ila_1_0 || ORIG_REF_NAME==MercuryZX1_system_ila_1_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_system_ila_2_0/MercuryZX1_system_ila_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_system_ila_2_0 || ORIG_REF_NAME==MercuryZX1_system_ila_2_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_system_ila_3_0/MercuryZX1_system_ila_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_system_ila_3_0 || ORIG_REF_NAME==MercuryZX1_system_ila_3_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_system_ila_4_0/MercuryZX1_system_ila_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_system_ila_4_0 || ORIG_REF_NAME==MercuryZX1_system_ila_4_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_system_ila_5_0/MercuryZX1_system_ila_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_system_ila_5_0 || ORIG_REF_NAME==MercuryZX1_system_ila_5_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_xlslice_0_0/MercuryZX1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_xlslice_0_0 || ORIG_REF_NAME==MercuryZX1_xlslice_0_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_xlslice_1_0/MercuryZX1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_xlslice_1_0 || ORIG_REF_NAME==MercuryZX1_xlslice_1_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_xlslice_2_0/MercuryZX1_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_xlslice_2_0 || ORIG_REF_NAME==MercuryZX1_xlslice_2_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_xlslice_3_0/MercuryZX1_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_xlslice_3_0 || ORIG_REF_NAME==MercuryZX1_xlslice_3_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_labtools_fmeter_0_0/MercuryZX1_labtools_fmeter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_labtools_fmeter_0_0 || ORIG_REF_NAME==MercuryZX1_labtools_fmeter_0_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_vio_0_0/MercuryZX1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_vio_0_0 || ORIG_REF_NAME==MercuryZX1_vio_0_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_xlconcat_1_0/MercuryZX1_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_xlconcat_1_0 || ORIG_REF_NAME==MercuryZX1_xlconcat_1_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_system_ila_0_0/MercuryZX1_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_system_ila_0_0 || ORIG_REF_NAME==MercuryZX1_system_ila_0_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_xlconcat_0_0/MercuryZX1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_xlconcat_0_0 || ORIG_REF_NAME==MercuryZX1_xlconcat_0_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_axi_gpio_0_0/MercuryZX1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_axi_gpio_0_0 || ORIG_REF_NAME==MercuryZX1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_proc_sys_reset_0/MercuryZX1_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_proc_sys_reset_0 || ORIG_REF_NAME==MercuryZX1_proc_sys_reset_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_processing_system7_1_0/MercuryZX1_processing_system7_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_processing_system7_1_0 || ORIG_REF_NAME==MercuryZX1_processing_system7_1_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_xbar_0/MercuryZX1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_xbar_0 || ORIG_REF_NAME==MercuryZX1_xbar_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_processing_system7_1_axi_periph_0/MercuryZX1_processing_system7_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_processing_system7_1_axi_periph_0 || ORIG_REF_NAME==MercuryZX1_processing_system7_1_axi_periph_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_rst_mig_7series_0_100M_0/MercuryZX1_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==MercuryZX1_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_xadc_wiz_0_0/MercuryZX1_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_xadc_wiz_0_0 || ORIG_REF_NAME==MercuryZX1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_vio_0_1/MercuryZX1_vio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_vio_0_1 || ORIG_REF_NAME==MercuryZX1_vio_0_1} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_auto_pc_3/MercuryZX1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_auto_pc_3 || ORIG_REF_NAME==MercuryZX1_auto_pc_3} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_auto_pc_0/MercuryZX1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_auto_pc_0 || ORIG_REF_NAME==MercuryZX1_auto_pc_0} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_auto_pc_1/MercuryZX1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_auto_pc_1 || ORIG_REF_NAME==MercuryZX1_auto_pc_1} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_auto_pc_2/MercuryZX1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_auto_pc_2 || ORIG_REF_NAME==MercuryZX1_auto_pc_2} -quiet] -quiet

# IP: bd/MercuryZX1/ip/MercuryZX1_auto_cc_0/MercuryZX1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MercuryZX1_auto_cc_0 || ORIG_REF_NAME==MercuryZX1_auto_cc_0} -quiet] -quiet

# XDC: bd/MercuryZX1/MercuryZX1_ooc.xdc
