webtalk_init -webtalk_dir /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/SdkExport/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-10-23 16:40:11" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174118286_178937913_210573335_948" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pa50jnfbbp7qoatjv75oucfvob" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_18" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "KDE neon User Edition 5.16" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen Threadripper 2950X 16-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1916.028 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.426 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1571841821000" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key Device -value "7z030" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1571841821000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1571845211935"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1571845211935"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1571845211935"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1571845211935"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1571845211935"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1571845211935"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1571845211935"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1571845211935"
webtalk_transmit -clientid 167365945 -regid "174118286_178937913_210573335_948" -xml /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/SdkExport/webtalk/usage_statistics_ext_sdk.xml -html /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/SdkExport/webtalk/usage_statistics_ext_sdk.html -wdm /media/2TB/workspace/rsarwar/work/enclastra/pe1_zx1/mercury_pe1_fmc104/SdkExport/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
